---
title: "NosAnalizamos"
author: "Carlos Albiach Melgar"
date: "`r Sys.Date()`" #fecha actual
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1 Elegir plantilla
2 cargar librerias
3 borrar variables
4 carga de datos(hacer encoding)


# Carga de librerias
```{r}
# VIM, deducorrect, GGally hacen las representaciones de datos faltantes
library(pacman)
p_load(tidyverse,readr,mice,knitr,validate,deducorrect,VIM,GGally)
```

# Borrar Variables
```{r}
# HACER SIEMPRE
rm(list = ls())
```

# Cargar datos
```{r}
datos <- read_delim("data/NosAutoanalizamos2022 - Hoja1.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE, skip = 25)

guess_encoding("data/NosAutoanalizamos2022 - Hoja1.tsv") # comprueba el encoding del archivo
head(datos)
datos <- datos %>% select(-c("...1")) %>% filter(Id != "martsobm")

```
# Asignaturas
```{r}
notas <- c("ALG", "ANM", "FP", "DCS", "MD")

datos <- datos %>% 
  mutate(across(13:17, ~ ifelse(. == "NC", 3, .))) %>% mutate(across(13:17, ~ as.numeric(.)))

# Revisa esas 5 columnas fila por fila. Si encuentra que la calificación es "NC" (No Calificado o No Presentado), la sustituye automáticamente por un 3. Si tiene cualquier otro valor, lo deja tal cual.
# Convierte esas mismas 5 columnas a tipo numérico.

Notas <- datos %>% select(Id, all_of(notas))

save(Notas, file = "Notas.Rdata")
```

# Calcular estadísticos
```{r}
datos %>% summarise(across(where(is.numeric),
                                 list(
                                   media= ~mean(.x, na.rm=TRUE),
                                   minimo = ~min(.x, na.rm=TRUE),
                                   per_25 = ~quantile(.x,0.25, na.rm= TRUE),
                                   maximo = ~max(.x, na.rm= TRUE),
                                   per_75 = ~quantile(.x, 0.75, na.rm= TRUE),
                                   desv= ~sd(.x,na.rm=TRUE),
                                   mediana= ~median(.x, na.rm=TRUE)
                                 ))) 
```

```{r warning=FALSE}
library(GGally)
ggpairs(datos %>% select(where(is.numeric)))

```

